version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 10
    directories:
    - "/infra/**"
    schedule:
      interval: "weekly"
