---
name: nvmf-rdma-test

on:
  workflow_dispatch:
    inputs:
      gerrit_ref:
        description: 'Gerrit refspec to test following refs/changes/${change_number: -2}/${change_number}/${patch_set} format'
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      client_payload:
        required: false
        type: string
        default: ''

jobs:
  hpe-nvmf-rdma:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      gerrit_ref: ${{ inputs.client_payload != '' && fromJson(inputs.client_payload).patchSet.ref || inputs.gerrit_ref }}
      spdk_path: './spdk'
    steps:
    - name: autorun-nvmf
      run: |
        for i in $(seq 1 30); do
          echo "Sleeping ..."
        done
        false
